package com.dongua.simpleosc.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dongua.simpleosc.bean.News;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS".
*/
public class NewsDao extends AbstractDao<News, Long> {

    public static final String TABLENAME = "NEWS";

    /**
     * Properties of entity News.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property NewsId = new Property(2, int.class, "newsId", false, "NEWS_ID");
        public final static Property Author = new Property(3, String.class, "author", false, "AUTHOR");
        public final static Property AuthorId = new Property(4, int.class, "authorId", false, "AUTHOR_ID");
        public final static Property Type = new Property(5, String.class, "type", false, "TYPE");
        public final static Property PubDate = new Property(6, String.class, "pubDate", false, "PUB_DATE");
        public final static Property CommentCount = new Property(7, int.class, "commentCount", false, "COMMENT_COUNT");
        public final static Property Object = new Property(8, int.class, "object", false, "OBJECT");
    }


    public NewsDao(DaoConfig config) {
        super(config);
    }
    
    public NewsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"NEWS_ID\" INTEGER NOT NULL ," + // 2: newsId
                "\"AUTHOR\" TEXT," + // 3: author
                "\"AUTHOR_ID\" INTEGER NOT NULL ," + // 4: authorId
                "\"TYPE\" TEXT," + // 5: type
                "\"PUB_DATE\" TEXT," + // 6: pubDate
                "\"COMMENT_COUNT\" INTEGER NOT NULL ," + // 7: commentCount
                "\"OBJECT\" INTEGER NOT NULL );"); // 8: object
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, News entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getNewsId());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
        stmt.bindLong(5, entity.getAuthorId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
 
        String pubDate = entity.getPubDate();
        if (pubDate != null) {
            stmt.bindString(7, pubDate);
        }
        stmt.bindLong(8, entity.getCommentCount());
        stmt.bindLong(9, entity.getObject());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, News entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getNewsId());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
        stmt.bindLong(5, entity.getAuthorId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
 
        String pubDate = entity.getPubDate();
        if (pubDate != null) {
            stmt.bindString(7, pubDate);
        }
        stmt.bindLong(8, entity.getCommentCount());
        stmt.bindLong(9, entity.getObject());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public News readEntity(Cursor cursor, int offset) {
        News entity = new News( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.getInt(offset + 2), // newsId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // author
            cursor.getInt(offset + 4), // authorId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // pubDate
            cursor.getInt(offset + 7), // commentCount
            cursor.getInt(offset + 8) // object
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, News entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNewsId(cursor.getInt(offset + 2));
        entity.setAuthor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAuthorId(cursor.getInt(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPubDate(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCommentCount(cursor.getInt(offset + 7));
        entity.setObject(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(News entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(News entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(News entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
