package com.dongua.simpleosc.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dongua.simpleosc.bean.PostBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POST_BEAN".
*/
public class PostBeanDao extends AbstractDao<PostBean, Long> {

    public static final String TABLENAME = "POST_BEAN";

    /**
     * Properties of entity PostBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DbID = new Property(0, Long.class, "dbID", true, "_id");
        public final static Property Id = new Property(1, int.class, "id", false, "ID");
        public final static Property Author = new Property(2, String.class, "author", false, "AUTHOR");
        public final static Property PubDate = new Property(3, String.class, "pubDate", false, "PUB_DATE");
        public final static Property PubDateLong = new Property(4, long.class, "pubDateLong", false, "PUB_DATE_LONG");
        public final static Property Authorid = new Property(5, int.class, "authorid", false, "AUTHORID");
        public final static Property Portrait = new Property(6, String.class, "portrait", false, "PORTRAIT");
        public final static Property Title = new Property(7, String.class, "title", false, "TITLE");
        public final static Property ViewCount = new Property(8, int.class, "viewCount", false, "VIEW_COUNT");
        public final static Property AnswerCount = new Property(9, int.class, "answerCount", false, "ANSWER_COUNT");
        public final static Property AnswerName = new Property(10, String.class, "answerName", false, "ANSWER_NAME");
        public final static Property AnswerTime = new Property(11, String.class, "answerTime", false, "ANSWER_TIME");
    }


    public PostBeanDao(DaoConfig config) {
        super(config);
    }
    
    public PostBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POST_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: dbID
                "\"ID\" INTEGER NOT NULL UNIQUE ," + // 1: id
                "\"AUTHOR\" TEXT," + // 2: author
                "\"PUB_DATE\" TEXT," + // 3: pubDate
                "\"PUB_DATE_LONG\" INTEGER NOT NULL ," + // 4: pubDateLong
                "\"AUTHORID\" INTEGER NOT NULL ," + // 5: authorid
                "\"PORTRAIT\" TEXT," + // 6: portrait
                "\"TITLE\" TEXT," + // 7: title
                "\"VIEW_COUNT\" INTEGER NOT NULL ," + // 8: viewCount
                "\"ANSWER_COUNT\" INTEGER NOT NULL ," + // 9: answerCount
                "\"ANSWER_NAME\" TEXT," + // 10: answerName
                "\"ANSWER_TIME\" TEXT);"); // 11: answerTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PostBean entity) {
        stmt.clearBindings();
 
        Long dbID = entity.getDbID();
        if (dbID != null) {
            stmt.bindLong(1, dbID);
        }
        stmt.bindLong(2, entity.getId());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
 
        String pubDate = entity.getPubDate();
        if (pubDate != null) {
            stmt.bindString(4, pubDate);
        }
        stmt.bindLong(5, entity.getPubDateLong());
        stmt.bindLong(6, entity.getAuthorid());
 
        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(7, portrait);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
        stmt.bindLong(9, entity.getViewCount());
        stmt.bindLong(10, entity.getAnswerCount());
 
        String answerName = entity.getAnswerName();
        if (answerName != null) {
            stmt.bindString(11, answerName);
        }
 
        String answerTime = entity.getAnswerTime();
        if (answerTime != null) {
            stmt.bindString(12, answerTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PostBean entity) {
        stmt.clearBindings();
 
        Long dbID = entity.getDbID();
        if (dbID != null) {
            stmt.bindLong(1, dbID);
        }
        stmt.bindLong(2, entity.getId());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
 
        String pubDate = entity.getPubDate();
        if (pubDate != null) {
            stmt.bindString(4, pubDate);
        }
        stmt.bindLong(5, entity.getPubDateLong());
        stmt.bindLong(6, entity.getAuthorid());
 
        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(7, portrait);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
        stmt.bindLong(9, entity.getViewCount());
        stmt.bindLong(10, entity.getAnswerCount());
 
        String answerName = entity.getAnswerName();
        if (answerName != null) {
            stmt.bindString(11, answerName);
        }
 
        String answerTime = entity.getAnswerTime();
        if (answerTime != null) {
            stmt.bindString(12, answerTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PostBean readEntity(Cursor cursor, int offset) {
        PostBean entity = new PostBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // dbID
            cursor.getInt(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // author
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // pubDate
            cursor.getLong(offset + 4), // pubDateLong
            cursor.getInt(offset + 5), // authorid
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // portrait
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // title
            cursor.getInt(offset + 8), // viewCount
            cursor.getInt(offset + 9), // answerCount
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // answerName
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // answerTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PostBean entity, int offset) {
        entity.setDbID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.getInt(offset + 1));
        entity.setAuthor(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPubDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPubDateLong(cursor.getLong(offset + 4));
        entity.setAuthorid(cursor.getInt(offset + 5));
        entity.setPortrait(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTitle(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setViewCount(cursor.getInt(offset + 8));
        entity.setAnswerCount(cursor.getInt(offset + 9));
        entity.setAnswerName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAnswerTime(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PostBean entity, long rowId) {
        entity.setDbID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PostBean entity) {
        if(entity != null) {
            return entity.getDbID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PostBean entity) {
        return entity.getDbID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
